### ISSUE TITLE
Optional parameter for returning more than one (all?) possible analysis

### ISSUE THREAD

**Issue by e-gor** [ixa-ehu/ixa-pipe-pos#2]
For example, in Spanish, for the word "agotado", it should return the analysis (agotar V) and (agotado A)

**Comment by ragerri** [comment]
If you run ixa-pipe-pos-1.5.1.jar with the option "-a" you can now see all the possible postags and lemmas in the morphofeat attribute in NAF. If you add also "-o conll"  you can see in tabulated format. De postag#lemma are ordered by the most probable to the least one.

han VAIP3P0#haber VMIP3P0#haber
pasado  VMP00SM#pasar NCMS000#pasado
factura NCFS000#factura VMIP3S0#facturar VMM02S0#facturar
al  SPCMS#al SP+DA#a+el

This also works in client server mode:

java -jar target/ixa-pipe-pos-1.5.1.jar server -l es -m morph-models-1.5.0/es/es-pos-perceptron-autodict01-ancora-2.0.bin -lm morph-models-1.5.0/es/es-lemma-perceptron-ancora-2.0.bin -p 2020 -a -o conll

or to NAF removing "-o conll option"
Let me know if this what you need and I will close the issue.

**Comment by ragerri** [comment]
This also works in client server mode: 

java -jar ../ixa-pipe-tok/target/ixa-pipe-tok-1.8.4.jar tok -l es | java -jar target/ixa-pipe-pos-1.5.1.jar server -l es -m morph-models-1.5.0/es/es-pos-perceptron-autodict01-ancora-2.0.bin -lm morph-models-1.5.0/es/es-lemma-perceptron-ancora-2.0.bin -p 2020 -a -o conll

or to NAF removing "-o conll option"
also, no need to include "all" after "-a"
Let me know if this what you need and I will close the issue.

**Comment by e-gor** [comment]
I have tried it and it works perfectly. Thanks very much!
