### ISSUE TITLE
Bug in pos server mode?

### ISSUE THREAD

**Issue by xavier-gz** [ixa-ehu/ixa-pipe-pos#8]
The --multiword (-mw) option doesn't seem to work in server mode.

1) we load tag an pos in server mode:

$ java -jar ixa-pipe-pos-master/targetxa-pipe-pos-1.5.2-exec.jar server -p 1235 -m morph-models-1.5.0/gl/gl-pos-perceptron-autdict05-ctag.bin -lm morph-models-1.5.0/gl/gl-lemma-perceptron-autodict05-ctag.bin -l gl -mw
CLI options: Namespace(allMorphology=false, lemmatizerModel=morph-models-1.5.0/gl/gl-lemma-perceptron-autodict05-ctag.bin, port=1235, beamSize=3, dictag=false, model=morph-models-1.5.0/gl/gl-pos-perceptron-autdict05-ctag.bin, language=gl, multiwords=true, outputFormat=naf)
ixa-pipe-pos model loaded in: 596 miliseconds ... [DONE]
ixa-pipe-lemma model loaded in: 97 miliseconds ... [DONE]
-> Trying to listen port... 1235
-> Connected and listening to port 1235

2) The multiword "de súpeto" is not recognised in server mode:

$ echo "Morreu de súpeto" | java -jar ixa-pipe-tok-master/target/ixa-pipe-tok-2.0.0-exec.jar client -p 1234 | java -jar ixa-pipe-pos-master/target/ixa-pipe-pos-1.5.2-exec.jar client -p 1235
CLI options: Namespace(port=1235, host=localhost)
```
<?xml version="1.0" encoding="UTF-8"?>
<NAF xml:lang="gl" version="v1.naf">
  <nafHeader>
    <linguisticProcessors layer="text">
      <lp name="ixa-pipe-tok-gl" beginTimestamp="2017-07-26T12:04:00+0200" endTimestamp="2017-07-26T12:04:00+0200" version="2.0.0-UNKNOWN_REVISION" hostname="aslagoas" />
    </linguisticProcessors>
    <linguisticProcessors layer="terms">
      <lp name="ixa-pipe-pos-gl-pos-perceptron-autdict05-ctag" beginTimestamp="2017-07-26T12:04:00+0200" endTimestamp="2017-07-26T12:04:00+0200" version="1.5.2-UNKNOWN_REVISION" hostname="aslagoas" />
    </linguisticProcessors>
  </nafHeader>
  <text>
    <wf id="w1" offset="0" length="6" sent="1" para="1">Morreu</wf>
    <wf id="w2" offset="7" length="2" sent="1" para="1">de</wf>
    <wf id="w3" offset="10" length="6" sent="1" para="1">súpeto</wf>
  </text>
  <terms>
    <!--Morreu-->
    <term id="t1" type="open" lemma="morrer" pos="V" morphofeat="VIS3S00">
      <span>
        <target id="w1" />
      </span>
    </term>
    <!--de-->
    <term id="t2" type="close" lemma="de" pos="P" morphofeat="S">
      <span>
        <target id="w2" />
      </span>
    </term>
    <!--súpeto-->
    <term id="t3" type="open" lemma="súpeto" pos="N" morphofeat="NCMS0">
      <span>
        <target id="w3" />
      </span>
    </term>
  </terms>
</NAF>
```

3) But the multiword "de súpeto" is recognised in direct tag mode:

$ echo "Morreu de súpeto" | java -jar ixa-pipe-tok-master/target/ixa-pipe-tok-2.0.0-exec.jar client -p 1234 | java -jar ixa-pipe-pos-master/target/ixa-pipe-pos-1.5.2-exec.jar tag -m morph-models-1.5.0/gl/gl-pos-perceptron-autdict05-ctag.bin -lm morph-models-1.5.0/gl/gl-lemma-perceptron-autodict05-ctag.bin -l gl -mw
CLI options: Namespace(allMorphology=false, lemmatizerModel=morph-models-1.5.0/gl/gl-lemma-perceptron-autodict05-ctag.bin, beamSize=3, dictag=false, model=morph-models-1.5.0/gl/gl-pos-perceptron-autdict05-ctag.bin, language=gl, multiwords=true, outputFormat=naf)
ixa-pipe-pos model loaded in: 624 miliseconds ... [DONE]
ixa-pipe-lemma model loaded in: 123 miliseconds ... [DONE]
```
<?xml version="1.0" encoding="UTF-8"?>
<NAF xml:lang="gl" version="v1.naf">
  <nafHeader>
    <linguisticProcessors layer="text">
      <lp name="ixa-pipe-tok-gl" beginTimestamp="2017-07-26T11:59:15+0200" endTimestamp="2017-07-26T11:59:15+0200" version="2.0.0-UNKNOWN_REVISION" hostname="aslagoas" />
    </linguisticProcessors>
    <linguisticProcessors layer="terms">
      <lp name="ixa-pipe-pos-gl-pos-perceptron-autdict05-ctag" beginTimestamp="2017-07-26T11:59:16+0200" endTimestamp="2017-07-26T11:59:16+0200" version="1.5.2-UNKNOWN_REVISION" hostname="aslagoas" />
    </linguisticProcessors>
  </nafHeader>
  <text>
    <wf id="w1" offset="0" length="6" sent="1" para="1">Morreu</wf>
    <wf id="w2" offset="7" length="2" sent="1" para="1">de</wf>
    <wf id="w3" offset="10" length="6" sent="1" para="1">súpeto</wf>
  </text>
  <terms>
    <!--Morreu-->
    <term id="t1" type="open" lemma="morrer" pos="V" morphofeat="VIS3S00">
      <span>
        <target id="w1" />
      </span>
    </term>
    <!--de súpeto-->
    <term id="t2" type="open" lemma="de#súpeto" pos="A" morphofeat="R0">
      <span>
        <target id="w2" />
        <target id="w3" />
      </span>
    </term>
  </terms>
</NAF>

```

**Comment by ragerri** [comment]
fixed
